export const CATEGORIES = ["Tops", "Bottoms", "Caps", "Shoes", "Outerwear"];

export const PRODUCTS = [
  {
    id: "shoe-1",
    name: "Nike Grey Navy — Lime Accent",
    category: "Shoes",
    price: 3000,
    image_url: "/images/products/shoe-1.jpg",
    description: "",
    origin: "",
    era: "",
    condition_rating: null,
    rarity: "Uncommon",
    size: "",
    status: "available",
    featured: true,
  },
  {
    id: "shoe-2",
    name: "Adidas Superstar — White Purple",
    category: "Shoes",
    price: 3000,
    image_url: "/images/products/shoe-2.jpg",
    description: "",
    origin: "",
    era: "",
    condition_rating: null,
    rarity: "Uncommon",
    size: "",
    status: "available",
    featured: true,
  },
  {
    id: "shoe-3",
    name: "Nike Air Force 1 — Mocha",
    category: "Shoes",
    price: 3000,
    image_url: "/images/products/shoe-3.jpg",
    description: "",
    origin: "",
    era: "",
    condition_rating: null,
    rarity: "Rare",
    size: "",
    status: "available",
    featured: true,
  },
  {
    id: "shoe-4",
    name: "Nike SB Dunk Low — White Black Gum",
    category: "Shoes",
    price: 3000,
    image_url: "/images/products/shoe-4.jpg",
    description: "",
    origin: "",
    era: "",
    condition_rating: null,
    rarity: "Rare",
    size: "",
    status: "available",
    featured: false,
  },
  {
    id: "shoe-5",
    name: "Adidas Denim Wash Sneaker",
    category: "Shoes",
    price: 3000,
    image_url: "/images/products/shoe-5.jpg",
    description: "",
    origin: "",
    era: "",
    condition_rating: null,
    rarity: "Rare",
    size: "",
    status: "available",
    featured: false,
  },
  {
    id: "shoe-6",
    name: "Jordan Stadium 90 — White Grey",
    category: "Shoes",
    price: 3000,
    image_url: "/images/products/shoe-6.jpg",
    description: "",
    origin: "",
    era: "",
    condition_rating: null,
    rarity: "Rare",
    size: "",
    status: "available",
    featured: false,
  },
  {
    id: "shoe-7",
    name: "Nike SB Dunk Low — Cherry",
    category: "Shoes",
    price: 3000,
    image_url: "/images/products/shoe-7.jpg",
    description: "",
    origin: "",
    era: "",
    condition_rating: null,
    rarity: "Grail",
    size: "",
    status: "available",
    featured: false,
  },
  {
    id: "shoe-8",
    name: "Puma Suede 1968 — Black Gold",
    category: "Shoes",
    price: 3000,
    image_url: "/images/products/shoe-8.jpg",
    description: "",
    origin: "",
    era: "",
    condition_rating: null,
    rarity: "Uncommon",
    size: "",
    status: "available",
    featured: false,
  },
  {
    id: "shoe-9",
    name: "Adidas Grand Court — White Black",
    category: "Shoes",
    price: 3000,
    image_url: "/images/products/shoe-9.jpg",
    description: "",
    origin: "",
    era: "",
    condition_rating: null,
    rarity: "Common",
    size: "",
    status: "available",
    featured: false,
  },
  {
    id: "shoe-10",
    name: "Converse Chuck Taylor Low — Black",
    category: "Shoes",
    price: 3000,
    image_url: "/images/products/shoe-10.jpg",
    description: "",
    origin: "",
    era: "",
    condition_rating: null,
    rarity: "Common",
    size: "",
    status: "available",
    featured: false,
  },
];